spring:
  datasource:
    url: jdbc:mysql://43.138.86.62:3306/erupt?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
  profiles:
    active: dev
server:
  port: 8888

# 文件共享位置
erupt:
#  uploadPath: /Users/hongyan/Desktop/shuke/shareFiles
  uploadPath: /soft/data