spring:
  datasource:
    url: jdbc:mysql://47.95.36.245:3306/erupt?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB

  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
  profiles:
    active: dev
server:
  port: 8889

# 文件共享位置
erupt:
#  uploadPath: /Users/hongyan/Desktop/shuke/shareFiles
  uploadPath: /soft/data
#  uploadPath: C:\My_Work\IdeaProjects\data